services:
  build-linux:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./target:/app/src-tauri/target
    working_dir: /app
    platform: linux/amd64
    environment:
      TAURI_PRIVATE_KEY: ${TAURI_PRIVATE_KEY}
      TAURI_KEY_PASSWORD: ${TAURI_KEY_PASSWORD}
      APPLE_SIGNING_IDENTITY: ${APPLE_SIGNING_IDENTITY}
    command: "npm run tauri build -- --target x86_64-unknown-linux-gnu"
