on:
  push:
    branches: [main, release]
  pull_request:
name: Build Flatpak
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-24.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: jochumdev/flatpak-github-actions/flatpak-builder@builder-update-deps
        with:
          bundle: org.jousse.vincent.Pomodorolm
          manifest-path: flatpak/org.jousse.vincent.Pomodorolm.yml
          cache-key: flatpak-builder-${{ github.sha }}
          upload-artifact: false
