on:
  push:
    branches: [main, release]
  workflow_dispatch:

name: Build Flatpak
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: org.jousse.vincent.Pomodorolm
          manifest-path: flatpak/org.jousse.vincent.Pomodorolm.yml
          cache-key: flatpak-builder-${{ github.sha }}
          upload-artifact: false
